#!/bin/bash

export cert_name='www.example.com'

export service_username='certfetcher'
export local_pki_group='local_pki'

export system_pki_dir_base='/etc/pki'
export local_pki_dir="${system_pki_dir_base}/local"

date_time=$(date +%Y.%m.%d-%H.%M.%S)
backup_dir="${local_pki_dir}/old/${date_time}"
mkdir -v -p "${backup_dir}"
cp -v -p "${cert_name}"* "${backup_dir}"

# initial key/csr creation
export dn_section='req_dn_short-no_prompt'; \
openssl req \
    -new \
    -out "${cert_name}-csr.pem"

chgrp local_pki "${cert_name}"*
touch "${cert_name}-cert.pem"
chown "${service_username}.${local_pki_group}" "${cert_name}-cert.pem"
chmod -v 'g+r' "${cert_name}"*
chmod -v 'o-r' "${cert_name}-key.pem"

unset cert_name
unset service_username
unset local_pki_group
unset system_pki_dir_base
unset local_pki_dir

exit 0
