#!/bin/bash

export org_name='dipswitch'
export cert_name='www.example.com'

export service_username='certfetcher'
export local_pki_group='local_pki'

export system_pki_dir_base='/etc/pki'
export local_pki_dir="${system_pki_dir_base}/local"
export home_pki_dir="${HOME}/pki"
export acme_dir='/srv/www/global/.well-known/acme-challenge'

# initial key/csr creation
export dn_section='req_dn_short-no_prompt'; \
openssl req \
    -new \
    -out "${cert_name}-csr.pem"

chgrp local_pki "${cert_name}"*
touch "${cert_name}-cert.pem"
chown "${service_username}.${local_pki_group}" "${cert_name}-cert.pem"
chmod 'g+r' "${cert_name}"*
chmod 'o-r' "${cert_name}-key.pem"

# certificate request
acme-tiny-reqcert \
  --ca 'https://acme-v01.api.letsencrypt.org' \
  --account-key "${home_pki_dir}/letsencrypt_account-${org_name}-key-rsa-private.pem" \
  --csr "/etc/pki/local/${cert_name}-csr.pem" \
  --acme-dir "${acme_dir}" \
  > "${local_pki_dir}/${cert_name}-cert.pem"

unset org_name
unset cert_name
unset service_username
unset local_pki_group
unset system_pki_dir_base
unset local_pki_dir
unset home_pki_dir
unset acme_dir

exit 0
