#!/bin/bash

export org_name='example_corp'

export service_username='certfetcher'
export local_pki_group='local_pki'
export httpd_operator_group='httpd_operators'

export system_pki_dir_base='/etc/pki'
export local_pki_dir="${system_pki_dir_base}/local"
export local_pki_backup_dir="${local_pki_dir}/old"
export home_pki_dir="${HOME}/pki"
export sudoers_file='/etc/sudoers.d/90-local'

export acme_dir='/srv/www/global/.well-known/acme-challenge'

groupadd "${local_pki_group}"
groupadd "${httpd_operator_group}"
usermod -aG "${local_pki_group}" "${service_username}"
usermod -aG "${httpd_operator_group}" "${service_username}"

printf "%%${httpd_operator_group}\t\t\tALL=(root)NOPASSWD:\t\t\t/usr/sbin/service apache2 reload\n" >> "${sudoers_file}"
chmod --verbose 0440 "${sudoers_file}"

mkdir --verbose --parent "${local_pki_dir}"
chmod --verbose 1775 "${local_pki_dir}"
chgrp --verbose "${local_pki_group}" "${local_pki_dir}"

mkdir --verbose --parent "${local_pki_dir}/old"
chgrp --verbose "${local_pki_group}" "${local_pki_dir}/old"
chmod --verbose 'g+w' "${local_pki_dir}/old"

cd "${local_pki_dir}"
chgrp --verbose "${local_pki_group}" *
chmod --verbose 'g+r' *

mkdir --verbose --parent "${system_pki_dir_base}/intermediate_authorities/letsencrypt"
cd "${system_pki_dir_base}/intermediate_authorities/letsencrypt"
curl -kvL 'https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem' -o 'lets_encrypt_authority_x3-dst_root-cert.pem'
curl -kvL 'https://letsencrypt.org/certs/letsencryptauthorityx3.pem' -o 'lets_encrypt_authority_x3-isrg_root-cert.pem'

mkdir --verbose --parent "/opt/${org_name}/bin"
cd "/opt/${org_name}/bin"
curl -vkLO 'https://raw.githubusercontent.com/junkb/cert_checker/master/cert_checker'
curl -vkLO 'https://raw.githubusercontent.com/junkb/cert_checker/master/cert_checker-cron'
curl -vkLO 'https://raw.githubusercontent.com/junkb/cert_checker/master/cert_checker-reload_prosody'
chmod --verbose '+x' cert*

mkdir --verbose --parent /opt/acme-tiny
cd /opt/acme-tiny
curl -vkLO 'https://raw.githubusercontent.com/junkb/acme-tiny/master/acme-tiny-reqcert'
chmod --verbose '+x' acme*

mkdir --verbose --parent "${acme_dir}"
chown --verbose "${service_username}.${service_username}" "${acme_dir}"

unset org_name
unset service_username
unset local_pki_group
unset httpd_operator_group
unset system_pki_dir_base
unset local_pki_dir
unset local_pki_backup_dir
unset home_pki_dir
unset acme_dir

exit 0
